language: php

addons:
  apt:
    packages:
      - oracle-java8-set-default

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - "7.0"
  - "5.5"

env:
  - WP_VERSION=latest WP_MULTISITE=1 ES_VERSION="5.0.2"
  - WP_VERSION=latest WP_MULTISITE=1 ES_VERSION="5.2.2"
  - WP_VERSION=latest WP_MULTISITE=1 ES_VERSION="5.5.1"

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch restart

before_script:
  - composer install --dev
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - sleep 10
