language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - "7.0"
  - "5.5"

env:
  - WP_VERSION=latest WP_MULTISITE=1

services:
  - elasticsearch

before_script:
  - composer install --dev
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - sleep 10
