language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - "7.0"
  - "5.3"

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=3.7.1 WP_MULTISITE=0
  - WP_VERSION=3.7.1 WP_MULTISITE=1

services:
  - elasticsearch

before_script:
  - if [ "$(phpenv version-name)" != "5.2" ]; then composer install --dev; fi;
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - sleep 10
