language: php

php:
  - 7.2

notifications:
  email: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
    - node_modules
    - $HOME/vendor

env:
  global:
  - WP_VERSION=latest WP_MULTISITE=1 ES_VERSION="7.5.0"

jobs:
  fast_finish: true
  include:
    - stage: "ElasticPress Tests"
      name: "Unit Tests"
      script: composer run-script test
      before_install:
        - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION-amd64.deb
        - sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION-amd64.deb
        - sudo sed -i.old 's/-Xms1g/-Xms128m/' /etc/elasticsearch/jvm.options
        - sudo sed -i.old 's/-Xmx1g/-Xmx128m/' /etc/elasticsearch/jvm.options
        - echo -e '-XX:+DisableExplicitGC\n-Djdk.io.permissionsUseCanonicalPath=true\n-Dlog4j.skipJansi=true\n-server\n' | sudo tee -a /etc/elasticsearch/jvm.options
        - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
        - sudo service elasticsearch restart
      before_script:
        - composer install
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        - sleep 10
    - script: if [ -n "$AWS_ACCESS_KEY" ]; then bash run-wpacceptance.sh; fi
      name: "WP Acceptance Test"
      before_script:
        - composer install
        - npm install
        - if [ -n "$AWS_ACCESS_KEY" ]; then ./vendor/bin/wpsnapshots configure 10up --aws_key=$AWS_ACCESS_KEY --aws_secret=$SECRET_ACCESS_KEY --user_name=Travis --user_email=travis@10up.com; fi
    - script: composer run-script lint
      name: "Linting"
      before_script:
        - composer install