language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - "7.0"
  - "5.5"

env:
  - WP_VERSION=latest WP_MULTISITE=1

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.2.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.2.2.deb && sudo service elasticsearch restart

before_script:
  - composer install --dev
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - sleep 10
