<?php
/**
 * Plugin Name:       ElasticPress Proxy - AutoSuggestV2 New
 * Description:       A custom PHP Proxy to handle Instant Results requests.
 * Version:           1.0.0
 * Author:            10up | ElasticPress.io
 * Author URI:        https://elasticpress.io
 * Text Domain:       autosuggestv2-proxy-plugin
 * Domain Path:       /languages
 * Update URI:        https://github.com/10up/elasticpress-proxy
 * Requires at least: 5.6
 * Requires PHP:      7.0
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 *
 * @package ElasticPress_Custom_Proxy
 */

namespace ElasticPress_AS_Custom_Proxy;

use ElasticPress\Indexables;
use ElasticPress\Utils;

defined( 'ABSPATH' ) || exit;

/**
 * Enable the Instant Results feature.
 */
add_filter( 'ep_autosuggest_v2_available', '__return_true' );

/**
 * Save the a PHP file with the search query template and the post index URL into the uploads folder.
 *
 * @param string $search_template The search template.
 */
function save_template( $search_template ) {
	global $wp_filesystem;

	$post_index     = Indexables::factory()->get( 'post' )->get_index_name();
	$post_index_url = trailingslashit( Utils\get_host( true ) ) . $post_index;

	require_once ABSPATH . '/wp-admin/includes/file.php';
	WP_Filesystem();

	$file_content = array(
		'<?php',
		'// This file is automatically generated. DO NOT MODIFY IT.',
		'$post_index_url = \'' . $post_index_url . '\';',
		'$query_template = \'' . $search_template . '\';',
		'',
	);

	$file_content = implode( "\n", $file_content );

	$uploads_dir = wp_upload_dir();

	$wp_filesystem->put_contents(
		trailingslashit( $uploads_dir['basedir'] ) . 'ep-custom-proxy-credentials.php',
		$file_content
	);
}
add_action( 'ep_autosuggest_v2_template_saved', __NAMESPACE__ . '\save_template' );

/**
 * Set the custom proxy as the search endpoint.
 *
 * @return string
 */
function set_proxy() {
	return plugin_dir_url( __FILE__ ) . 'autosuggestv2-proxy.php';
}
add_filter( 'ep_autosuggest_v2_search_endpoint', __NAMESPACE__ . '\set_proxy' );
