name: 'Close stale issues'

# **What it does**: Closes issues where the original author doesn't respond to a request for information.
# **Why we have it**: To remove the need for maintainers to remember to check back on issues periodically to see if contributors have responded.

on:
  schedule:
    # Schedule for every day at 1:30am UTC
    - cron: '30 1 * * *'

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 7
          days-before-close: 7
          stale-issue-message: >
            It has been 7 days since more information was requested from you in this issue and we have not heard back. This issue is now marked as stale and will be closed in 7 days, but if you have more information to add then please comment and the issue will stay open.
          close-issue-message: >
            This issue has been automatically closed because there has been no response
            to our request for more information. With only the
            information that is currently in the issue, we don't have enough information
            to take action. Please reach out if you have or find the answers we need so
            that we can investigate further. See [this blog post on bug reports and the
            importance of repro steps](https://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/)
            for more information about the kind of information that may be helpful.
          stale-issue-label: 'stale'
          close-issue-reason: 'not_planned'
          any-of-labels: 'reporter feedback'
          remove-stale-when-updated: true
          
