name: E2E Test

env:
  NODE_VERSION: "12"
  NODE_CACHE: "${{ github.workspace }}/node_modules_cache"

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare npm cache
      uses: actions/cache@v2
      with:
        path: ${{ env.NODE_CACHE }}
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ env.NODE_VERSION }}-

    - name: "Install node v${{ env.NODE_VERSION }}"
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm i

    - name: Set up WP environment with Elasticsearch
      run: npm run env:start

    - name: Build asset
      run: npm run build

    - name: Set up database
      run: npm run cypress:setup

    - name: Test
      run: npm run cypress:run

    - name: Make artifacts available
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-artifact
        retention-days: 2
        path: |
          ${{ github.workspace }}/tests/cypress/screenshots/
          ${{ github.workspace }}/tests/cypress/videos/

    - name: Stop Elasticsearch
      if: always()
      run: cd bin/es-docker/ && docker-compose down
