name: E2E Test

env:
  NODE_VERSION: "12"
  NODE_CACHE: "${{ github.workspace }}/node_modules_cache"

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Elasticsearch
      run: cd bin/es-docker/ && docker-compose up -d

    - name: Prepare npm cache
      uses: actions/cache@v2
      with:
        path: ${{ env.NODE_CACHE }}
        key: npm-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ env.NODE_VERSION }}-

    - name: "Install node v${{ env.NODE_VERSION }}"
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm i

    - name: Build asset
      run: npm run build

    - name: Set up WP environment
      run: npm run env start && ./bin/setup-cypress-env.sh

    - name: Test
      run: npm run cypress:run

    - name: Stop Elasticsearch
      if: always()
      run: cd bin/es-docker/ && docker-compose down
