name: Publish elasticpress-playwright-utils

on:
  push:
    branches:
      - develop
      - trunk
      - chore/bump-playwright-utils-version

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install npm
        run: npm install -g npm@latest

      - run: npm ci

      - run: npm test --if-present
        working-directory: tests/e2e

      - run: npm publish --access public
        working-directory: tests/e2e
