name: Publish New Release

env:
  SLUG: "elasticpress"

on:
  release:
    types: [published]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: |
        echo "${{ github.event_name }}"
        echo "${{ github.event.action }}"
        exit 1

    - name: Checkout code
      uses: actions/checkout@v2

    - name: install node v10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Build
      run: |
        npm install
        npm run build

    - name: WordPress Plugin Deploy
      if: "github.event_name == 'release' && github.event.action == 'released'"
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: ${{ env.SLUG }}

    - name: Create ZIP
      run: |
        TMP_DIR="${HOME}/archive/${{ env.SLUG }}"
        mkdir -p $TMP_DIR
        rsync -rc --exclude-from="${{ github.workspace }}/.distignore" "${{ github.workspace }}/" "$TMP_DIR/" && cd $TMP_DIR/.. && zip -r "${{ github.workspace }}/${{ env.SLUG }}.zip" .

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/${{ env.SLUG }}.zip
        asset_name: elasticpress-${{ github.ref_name }}.zip
        asset_content_type: application/zip