name: Deploy to WordPress.org
on:
  release:
    types: [published]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install node v10
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Build
      run: |
        npm install
        npm run build

    - name: Create ZIP
      if: "contains(github.ref_name, 'beta')"
      run: |
        git archive --prefix=distributor/ HEAD -o ${{ github.event.repository.name }}.zip

    - name: WordPress Plugin Deploy
      if: "!contains(github.ref_name, 'beta')"
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
        asset_name: ${{ github.event.repository.name }}.zip
        asset_content_type: application/zip