name: Spell Check

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run typos
        uses: crate-ci/typos@master
